### ISSUE TITLE
Hardware change list for rev3

### ISSUE THREAD

**Issue by festlv** [open-lv/air-guard#15]
* 220uF electrolytic capacitor near ESP32/MHZ19
* Fatter 5V/GND traces (at least from ESP32 to MHZ19)

**Comment by skrubis** [comment]
[My last commit](https://github.com/open-lv/air-guard/commit/d39949ea450ae0b14a582b1f3dd6d0d9de07e22a) addresses the following:

- Added bulk capacitance close to esp32
- added more girth to 3v3, 5V and GND nets, added thermal reliefs where applicable
- fixed text from previous revision being mirrored where it should not be
- added a lot of text regarding the correct side for components/soldering
- cleaned up routing in general, made it a bit more compact
- added SAO 1.69ibis connector on the abdomen for future extendability
- covered up exposed traces on the neck
- lots of other various tiny tweaks
