### ISSUE TITLE
Plates (PCB) forma un noformējums

### ISSUE THREAD

**Issue by kasparsd** [open-lv/air-guard#3]
Kāda varētu būt PCB kontūra un noformējums, lai tas liktos interesants un iederētos klasēs un birojos?

Svarīgi ņemt vērā ārējo izmēru (cena) un praktiskās iespējas tādu formu saražot pietiekami mazos kvantumos, lai pieļautu izmaiņas. Pirmajām partijām varētu izmantot https://jlcpcb.com vai https://www.pcbway.com

**Comment by kasparsd** [comment]
Te ir jaunākais variants, kas ir mazliet draudzīgāks par vienkārši zaļu plati:

![gaisa-sargs-prototips-2](https://user-images.githubusercontent.com/169055/134526827-15b3b0ab-ad7e-4cb1-b12c-b7aa093daa55.jpg)

**Comment by martinsp** [comment]
Vai nevajadzētu samainīt vietām bateriju turētāju un radošo laukumu? Domāju, vai komponentes uz plates netraucēs rokai, lai varētu uzzīmēt/uzrakstīt kaut ko radošajā laukumā.

**Comment by kasparsd** [comment]
Taisām ciet, jo šis jau ir izdarīts!
