### ISSUE TITLE
Materiālu saraksts (bill of materials) -- kontrolieri, sensori un barošana

### ISSUE THREAD

**Issue by kasparsd** [open-lv/air-guard#7]
Provizoriskais materiālu saraksts (atjaunots 26. septembrī):

## Vietas sensoriem

- [MH-Z19b](https://www.winsen-sensor.com/sensors/co2-sensor/mh-z19b.html) CO2 sensors.
- DHT22 temperatūras un mitruma sensors.

Tukša vieta uz PCB vēl šādiem: 

- [SenseAir S8](https://senseair.com/products/size-counts/s8-residential/) CO2 sensors.
- [SCD41](https://www.sensirion.com/en/environmental-sensors/carbon-dioxide-sensors/carbon-dioxide-sensor-scd4x/) CO2, temperatūras, mitruma un trokšņa sensors. Šis ir surface-mount, tāpēc vajadzīga pārejas plate vai arī atbalsts esošiem moduļiem.
- [BME280](https://randomnerdtutorials.com/dht11-vs-dht22-vs-lm35-vs-ds18b20-vs-bme280-vs-bmp180/) temperatūras un mitruma sensors. 

## Barošana

Tika izlemts lietot patstāvīgu barošanu no USB, lai MVP versijā nebūtu jānodarbojas ar enerģijas patēriņa optimizācijas uzdevumu.

## Kontrolieris un ekrāns

- ESP32-DevKitC
- SSD1306 OLED ekrāns

**Comment by Anrijs** [comment]
MH-Z19B/C boost vajadzēs uz 5V

**Comment by kasparsd** [comment]
Izskatās, ka ESP32-DevKitC [padod USB 5V uz EXT_5V kāju](https://dl.espressif.com/dl/schematics/esp32_devkitc_v4-sch.pdf), kad pieslēgts USB:

![USB 5V power to T_5V](https://user-images.githubusercontent.com/169055/134800126-6e41beb9-6b42-4f9b-9202-cf11dc94bd1f.png)

Vai pareizi saprotu?

Šis, protams, der tikai tad, ja tiek lietots patstāvīgs USB pieslēgums, par kuru vakar nolēmām čatā.

**Comment by Anrijs** [comment]
Ja barošana paliek tikai no USB, tad var no tā EXT 5V pin barot

**Comment by kasparsd** [comment]
ESP32 devkitc piegādātāju opcijas:

- https://www.olimex.com/Products/IoT/ESP32/ESP32-DevKit-LiPo/open-source-hardware
- https://www.tme.eu/lv/details/esp32-devkitc-32d/komplekts-datu-transmisijai/espressif/
- https://www.az-delivery.de/en/products/esp-32-dev-kit-c-v4?variant=30871551901792

**Comment by kasparsd** [comment]
Esmu pasūtījis kopumā 15 gab. devkitc no diviem piegādātājiem un varēšu pārsūtīt visiem interesentiem.

**Comment by kasparsd** [comment]
Iedomājos, ka varētu paredzēt vietu vēl sekojošām komponentēm:

- on/off slēdzis. Var likt pie `EN` kājas, bet tas izslēdz tikai 3.3V barošanu pašam ESP32 un visam, kas barojas no tiem 3.3V. Alternatīva ir paredzēt vietu savam USB virsmaz montāžas štepselim uz plates, kas var pilnībā izslēgt visu iekārtu. Pieslēgvieta uz plates arī atļautu optimizēt tās novietojumu, lai plate negāztos uz galda vai nesvērtos pie sienas.

- Passive buzzeris, kas nodzied bēdīgu meldiņu, kad pārsniedz 1400PPM un priecīgu, kad ir atpakaļ zem 600 vai jebkuras citas iedomātas robežas. Buzzerim vajadzētu savu slēdzi, lai var apklusināt bez pārprogramēšanas. Šiem parasti ir divas kājas, kuras var iespraust ligzdā.

- Kaut kādus ledus? Varbūt zaļu, dzeltenu un sarkanu vai vairākus rindā, lai atvieglotu CO2 nolasīšanu no attāluma, jo dzīvē tas SSD1306 ir tiešām maziņš un blāvs?

**Comment by Anrijs** [comment]
~~`EN` varbūt labāk neaiztikt. Tas tiek izmantots priekš programmēšanas.~~ Sajaucu ar BOOT
Buzeris varētu būt noderīgs, bet tam jātaisa driveris vai jāmeklē gatava plate ar driveri. Slēgt vienu kāju pa tiešo pie ESP32 nebūs labs variants.
LED varētu būt noderīgi, lai var redzēt stāvokli arī no otra telpas stūra.
